# 3量化工作--NumPy

## 3.1并行化思想与基础操作

### 3.1.1并行化思想

In [1]:
# 官方推荐引用numpy
import numpy as np

In [3]:
normal_list = range(10000)
%timeit [i**2 for i in normal_list]

4.99 ms ± 257 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
np_list = np.arange(10000)
%timeit np_list**2

8.4 µs ± 360 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
# 注意 *3的操作被运作在每一个元素上
np_list = np.ones(5) * 3
print(np_list)
# 普通列表把*3操作认为是整体性操作
normal_list = [1, 1, 1, 1, 1] * 3
print(normal_list, len(normal_list))

[3. 3. 3. 3. 3.]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] 15


### 3.1.2初始化操作

In [7]:
# 100个0
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# shape:3行2列 全是0
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
# shape:3行2列 全是1
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# shape: x=2, y=3, z=3 值随机
np.empty((2, 3, 3))

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [9.79101081e-307, 2.22522868e-306, 1.42418987e-306],
        [1.37961641e-306, 1.60220528e-306, 1.24611266e-306]],

       [[9.34598925e-307, 1.24612081e-306, 1.11260755e-306],
        [1.60220393e-306, 1.51320640e-306, 9.34609790e-307],
        [1.86921279e-306, 1.24610723e-306, 2.56761491e-312]]])

In [17]:
# 初始化序列与np_list一样的shape，值全为1
np.ones_like(np_list)

array([1., 1., 1., 1., 1.])

In [19]:
# 初始化序列与np_list一样的shape，值全为0
np.zeros_like(np_list)

array([0., 0., 0., 0., 0.])

In [20]:
# eye()得到对角线全为1的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# 可以将普通list作为参数，通过np.array来初始化np array
data = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr_np = np.array(data)
arr_np

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
# linspace()等间隔生成序列，从0-1之间生成11个点（10等分）
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [27]:
# 200只股票
stock_cnt = 200
# 504个交易日
view_days = 504
# 生成服从正态分布：均值期望=0，标准差=1的序列
stock_day_change = np.random.standard_normal((stock_cnt, view_days))
# 打印shape：（200， 504）200行504列
print(stock_day_change.shape)
# 打印出第一只股票，前5个交易日的涨跌幅情况
print(stock_day_change[0:1, :5])


(200, 504)
[[ 0.52517348 -1.16028804 -0.52967753  0.18955958 -0.35173287]]


### 3.1.3索引选取和切片选择

In [28]:
# 0:2第一只、第二只股票， 0:5前5个交易日的涨跌幅数据
stock_day_change[0:2, 0:5]

array([[ 0.52517348, -1.16028804, -0.52967753,  0.18955958, -0.35173287],
       [ 0.1186008 , -1.66883187,  0.98415554,  0.83764362, -3.84483116]])

In [29]:
# -2:倒数第一只，第二只股票，-5最后5个交易日的涨跌幅数据
stock_day_change[-2:, -5:]

array([[-1.20889935, -1.13041004, -1.86480123, -1.44689217,  2.04584387],
       [ 1.8729086 , -1.27818982,  1.61455468, -0.32296673,  2.06806463]])

In [30]:
# tmp = a
tmp = stock_day_change[:2, :5].copy()
# a = b
stock_day_change[:2, :5] = stock_day_change[-2:, -5:]
# b = tmp
stock_day_change[-2:, -5:] = tmp
stock_day_change[:2, :5], stock_day_change[-2:, -5:]

(array([[-1.20889935, -1.13041004, -1.86480123, -1.44689217,  2.04584387],
        [ 1.8729086 , -1.27818982,  1.61455468, -0.32296673,  2.06806463]]),
 array([[ 0.52517348, -1.16028804, -0.52967753,  0.18955958, -0.35173287],
        [ 0.1186008 , -1.66883187,  0.98415554,  0.83764362, -3.84483116]]))

### 3.1.4数据转换与规整

In [32]:
print(stock_day_change[:2, :5])
stock_day_change[:2, :5].astype(int)

[[-1.20889935 -1.13041004 -1.86480123 -1.44689217  2.04584387]
 [ 1.8729086  -1.27818982  1.61455468 -0.32296673  2.06806463]]


array([[-1, -1, -1, -1,  2],
       [ 1, -1,  1,  0,  2]])

In [33]:
# 规整float数据
np.around(stock_day_change[:2, :5], 2)

array([[-1.21, -1.13, -1.86, -1.45,  2.05],
       [ 1.87, -1.28,  1.61, -0.32,  2.07]])